import { DataSourceType } from "./DataSourceType";

export const defaultData: DataSourceType[] = [
  {
    id: 1,
    friendlyId: "NM_001",
    status: "Active",
    associate: "câu hỏi 01",
    questionsNum: 10,
    type: "multiple",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 2,
    friendlyId: "NM_002",
    status: "Active",
    associate: "Câu hỏi 02",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "radio",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 3,
    friendlyId: "NM_003",
    status: "Active",
    associate: "Câu hỏi 03",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 4,
    friendlyId: "NM_004",
    status: "Active",
    associate: "Câu hỏi 04",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 5,
    friendlyId: "NM_005",
    status: "Active",
    associate: "câu hỏi 05",
    questionsNum: 10,
    type: "multiple",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 6,
    friendlyId: "NM_006",
    status: "Active",
    associate: "Câu hỏi 06",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "radio",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 7,
    friendlyId: "NM_007",
    status: "Active",
    associate: "Câu hỏi 07",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 8,
    friendlyId: "NM_008",
    status: "Active",
    associate: "Câu hỏi 08",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 9,
    friendlyId: "NM_009",
    status: "Active",
    associate: "câu hỏi 09",
    questionsNum: 10,
    type: "multiple",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 10,
    friendlyId: "NM_010",
    status: "Active",
    associate: "Câu hỏi 10",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "radio",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 11,
    friendlyId: "NM_011",
    status: "Active",
    associate: "Câu hỏi 11",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 12,
    friendlyId: "NM_012",
    status: "Active",
    associate: "Câu hỏi 12",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
];
