import { QuestionType } from "../../user-types/QuestionType";

export const defaultData: QuestionType[] = [
  {
    id: 0,
    friendlyId: "NM_001",
    status: "Active",
    associate: "Question Description 01",
    questionsNum: 10,
    type: "multiple",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 1,
    friendlyId: "NM_002",
    status: "Active",
    associate: "Question Description 02",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "radio",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 2,
    friendlyId: "NM_003",
    status: "InActive",
    associate: "Question Description 03",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 3,
    friendlyId: "NM_004",
    status: "Active",
    associate: "Question Description 04",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 4,
    friendlyId: "NM_005",
    status: "InActive",
    associate: "Question Description 05",
    questionsNum: 10,
    type: "multiple",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 5,
    friendlyId: "NM_006",
    status: "Active",
    associate: "Question Description 06",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "radio",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 6,
    friendlyId: "NM_007",
    status: "Active",
    associate: "Question Description 07",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 7,
    friendlyId: "NM_008",
    status: "Active",
    associate: "Question Description 08",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 8,
    friendlyId: "NM_009",
    status: "Active",
    associate: "Question Description 09",
    questionsNum: 10,
    type: "multiple",
    scoringMethod: "continuous",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 9,
    friendlyId: "NM_010",
    status: "Active",
    associate: "Question Description 10",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "radio",
    fraction: 20,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 10,
    friendlyId: "NM_011",
    status: "Active",
    associate: "Question Description 11",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 11,
    friendlyId: "NM_012",
    status: "InActive",
    associate: "Question Description 12",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 12,
    friendlyId: "NM_013",
    status: "Active",
    associate: "Question Description 13",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 13,
    friendlyId: "NM_014",
    status: "Active",
    associate: "Question Description 14",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 14,
    friendlyId: "NM_015",
    status: "Active",
    associate: "Question Description 15",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 15,
    friendlyId: "NM_016",
    status: "Active",
    associate: "Question Description 16",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 16,
    friendlyId: "NM_017",
    status: "Active",
    associate: "Question Description 17",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 17,
    friendlyId: "NM_018",
    status: "Active",
    associate: "Question Description 18",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 18,
    friendlyId: "NM_019",
    status: "InActive",
    associate: "Question Description 19",
    questionsNum: 10,
    type: "judge",
    scoringMethod: "continuous",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
  {
    id: 19,
    friendlyId: "NM_020",
    status: "InActive",
    associate: "Question Description 20",
    questionsNum: 10,
    scoringMethod: "continuous",
    type: "vacant",
    fraction: 50,
    lastModified: new Date(),
    created: new Date(),
  },
];
